// Lista completa de tecnologías de desarrollo web moderno
// Organizada por categorías para facilitar la búsqueda

export const TECH_CATEGORIES = [
  {
    name: 'Frontend Frameworks & Libraries',
    tags: [
      'React',
      'Next.js',
      'Vue.js',
      'Nuxt.js',
      'Angular',
      'Svelte',
      'SvelteKit',
      'Solid.js',
      'Astro',
      'Preact',
      'Alpine.js',
      'Lit',
      'Qwik',
      'Remix',
      'Gatsby',
      'Ember.js',
      'Backbone.js',
      'Mithril',
      'Stencil',
      'Inertia.js',
    ],
  },
  {
    name: 'CSS & Styling',
    tags: [
      'Tailwind CSS',
      'Bootstrap',
      'Material UI',
      'Chakra UI',
      'Shadcn/ui',
      'Radix UI',
      'Ant Design',
      'Semantic UI',
      'Bulma',
      'Styled Components',
      'Emotion',
      'CSS Modules',
      'Sass/SCSS',
      'Less',
      'PostCSS',
      'Panda CSS',
      'UnoCSS',
      'DaisyUI',
      'PrimeReact',
      'NextUI',
    ],
  },
  {
    name: 'JavaScript/TypeScript',
    tags: [
      'JavaScript',
      'TypeScript',
      'ES6+',
      'Node.js',
      'Deno',
      'Bun',
      'jQuery',
      'RxJS',
      'Zustand',
      'Redux',
      'MobX',
      'Recoil',
      'Jotai',
      'TanStack Query',
      'TanStack Router',
      'tRPC',
      'Zod',
      'SWR',
      'Axios',
      'Socket.io',
    ],
  },
  {
    name: 'Backend Frameworks',
    tags: [
      'Express.js',
      'NestJS',
      'Fastify',
      'Koa',
      'Hapi.js',
      'AdonisJS',
      'Laravel',
      'Symfony',
      'Django',
      'Flask',
      'FastAPI',
      'Ruby on Rails',
      'Spring Boot',
      'ASP.NET Core',
      'Phoenix (Elixir)',
      'Gin (Go)',
      'Echo (Go)',
      'Fiber (Go)',
      'Actix Web',
      'Rocket (Rust)',
    ],
  },
  {
    name: 'Databases',
    tags: [
      'PostgreSQL',
      'MySQL',
      'MariaDB',
      'SQLite',
      'MongoDB',
      'Firebase Firestore',
      'Supabase',
      'Prisma',
      'Drizzle ORM',
      'TypeORM',
      'Mongoose',
      'Sequelize',
      'Knex.js',
      'Redis',
      'PlanetScale',
      'Neon DB',
      'SQL Server',
      'Oracle DB',
      'DynamoDB',
      'Cassandra',
    ],
  },
  {
    name: 'DevOps & Cloud',
    tags: [
      'Docker',
      'Kubernetes',
      'AWS',
      'Google Cloud',
      'Azure',
      'Vercel',
      'Netlify',
      'Cloudflare',
      'Railway',
      'Fly.io',
      'Render',
      'Heroku',
      'DigitalOcean',
      'Linux',
      'Nginx',
      'Apache',
      'GitHub Actions',
      'CI/CD',
      'Terraform',
      'Ansible',
    ],
  },
  {
    name: 'Mobile & Desktop',
    tags: [
      'React Native',
      'Expo',
      'Flutter',
      'SwiftUI',
      'Kotlin',
      'Jetpack Compose',
      'Ionic',
      'Capacitor',
      'Cordova',
      'Electron',
      'Tauri',
      'Xamarin',
      '.NET MAUI',
      'Unity',
      'PWA',
    ],
  },
  {
    name: 'Testing',
    tags: [
      'Jest',
      'Vitest',
      'Playwright',
      'Cypress',
      'Testing Library',
      'React Testing Library',
      'Mocha',
      'Chai',
      'Jasmine',
      'Selenium',
      'Puppeteer',
      'Supertest',
      'MSW',
      'Karma',
      'Storybook',
    ],
  },
  {
    name: 'GraphQL & APIs',
    tags: [
      'GraphQL',
      'Apollo Client',
      'Apollo Server',
      'Relay',
      'REST API',
      'OpenAPI/Swagger',
      'Postman',
      'Hasura',
      'Prisma',
      'tRPC',
      'GRPC',
      'WebSockets',
      'Server-Sent Events',
      'Webhooks',
    ],
  },
  {
    name: 'Tools & Bundlers',
    tags: [
      'Webpack',
      'Vite',
      'Turbopack',
      'Parcel',
      'Rollup',
      'esbuild',
      'SWC',
      'Babel',
      'ESLint',
      'Prettier',
      'Husky',
      'lint-staged',
      'NPM',
      'Yarn',
      'pnpm',
      'TurboRepo',
      'Nx',
      'Lerna',
      'Biome',
      'Oxc',
    ],
  },
  {
    name: 'Authentication & Security',
    tags: [
      'NextAuth.js',
      'Auth.js',
      'Supabase Auth',
      'Clerk',
      'Auth0',
      'Firebase Auth',
      'OAuth',
      'JWT',
      'Passport.js',
      'Lucia',
      'bcrypt',
      'Helmet.js',
      'CORS',
      'CSRF Protection',
      'HTTPS/SSL',
    ],
  },
  {
    name: 'Payment & Commerce',
    tags: [
      'Stripe',
      'PayPal',
      'Mercado Pago',
      'Lemon Squeezy',
      'Midtrans',
      'WooCommerce',
      'Shopify',
      'Magento',
      'Snipcart',
      'RevenueCat',
    ],
  },
] as const

// Lista plana de todas las tecnologías (normalizada con capitalización consistente)
export const ALL_TECH_TAGS: string[] = TECH_CATEGORIES.flatMap(
  (category) => category.tags
).sort((a, b) => a.localeCompare(b))


